---
- stat: path=/tmp/openresty.tar.gz
  register: resty_tar

- stat: path=/usr/sbin/nginx
  register: resty_exe

- name: Update apt
  sudo: yes
  apt: update_cache=yes
  when: resty_exe.stat.exists == False

- name: Install required packages to compile Openresty from source
  apt: name={{ item }}
  with_items:
    - libreadline-dev
    - make
    - libncurses5-dev
    - libpcre3-dev
    - libssl-dev
    - perl
    - libxml2-dev   #Optional
    - libxslt-dev   #Optional
    - libgd-dev     #Optional
    - libgeoip-dev  #Optional
  when: resty_exe.stat.exists == False

- name: Download Openresty source
  get_url: url=http://openresty.org/download/ngx_openresty-{{ openresty_version }}.tar.gz dest=/tmp/openresty.tar.gz mode=0440
  when: resty_tar.stat.exists == False or resty_exe.stat.exists == False

- name: Extract Openresty tarball
  command: chdir=/tmp/ /bin/tar zxf openresty.tar.gz
  when: resty_tar.stat.exists == False or resty_exe.stat.exists == False

- name: Build configure command
  template: src=configure_command.j2 dest=/tmp/ngx_openresty-{{ openresty_version }}/ansible_build.sh mode=0777
  when: resty_exe.stat.exists == False

- name: Configure Openresty
  command: chdir=/tmp/ngx_openresty-{{ openresty_version }} ./ansible_build.sh
  when: resty_exe.stat.exists == False

- name: Compile Openresty
  command: chdir=/tmp/ngx_openresty-{{ openresty_version }} make
  when: resty_exe.stat.exists == False

- name: Install Openresty
  command: chdir=/tmp/ngx_openresty-{{ openresty_version }} make install
  when: resty_exe.stat.exists == False

- name: Service command
  template: src=service.j2 dest=/etc/init.d/nginx owner=root group=root mode=0777
  when: resty_exe.stat.exists == False

- name: Putting service in start up
  command: update-rc.d nginx defaults
  notify: restart nginx
  when: resty_exe.stat.exists == False